// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxemmzkjxqilfzrrevrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4ZW1temtqeHFpbGZ6cnJldnJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNzk3OTksImV4cCI6MjA2MDg1NTc5OX0.7IT8oDvAR_9mUCITttyAZaULaMdD-UYPoU4f9ln_rRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);